#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    a=n
    for i in range(1,11):
        print(a," x ",i," = ",n )
        n=n+a
